### ISSUE TITLE
Why not use "new" box-sizing best practices?

### ISSUE THREAD

**Issue by dariodev** [tachyons-css/tachyons-box-sizing#7]
Why not just use?:
```CSS
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
https://www.paulirish.com/2012/box-sizing-border-box-ftw/
